############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 80

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/mall-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: 203991
